// Advanced pricing — flat, per-unit, revenue-based, hybrid, tiered and volume
// discounts. Pure computation (no DB): given a plan and a usage, produce a
// price quote in micro USD.

/** The pricing model a plan uses. */
export type PricingModel = 'flat' | 'per_unit' | 'revenue_based' | 'hybrid' | 'tiered';

/** A volume tier: units from the previous tier's bound up to `upTo` (inclusive). */
export interface Tier {
  /** Inclusive upper bound of the tier in units (use Infinity for the last tier). */
  upTo: number;
  /** Per-unit price within this tier, in micro USD. */
  unitPriceMicroUsd: number;
}

/** A volume discount applied once usage reaches a threshold. */
export interface VolumeDiscount {
  /** Minimum total units to qualify for the discount. */
  minUnits: number;
  /** Discount fraction in [0, 1], e.g. 0.10 = 10% off. */
  discountPct: number;
}

/** A pricing plan. Only the fields relevant to `model` are used. */
export interface PricingPlan {
  model: PricingModel;
  /** Base fee charged regardless of usage (flat, hybrid). */
  baseFeeMicroUsd?: number;
  /** Per-unit price (per_unit, hybrid). */
  unitPriceMicroUsd?: number;
  /** Revenue share fraction in [0, 1] (revenue_based, hybrid). */
  revenueSharePct?: number;
  /** Tiers (tiered). */
  tiers?: Tier[];
  /** Optional volume discount applied on top of the usage portion. */
  volumeDiscount?: VolumeDiscount;
}

/** The usage to price. */
export interface Usage {
  /** Total units consumed (sessions, minutes, tokens, ...). */
  units: number;
  /** Revenue generated by the tenant, in micro USD (revenue_based, hybrid). */
  revenueMicroUsd?: number;
}

/** A price quote with a full breakdown. */
export interface PriceQuote {
  model: PricingModel;
  /** Total charge in micro USD (after any discount, floored at 0). */
  totalMicroUsd: number;
  baseFeeMicroUsd: number;
  /** Variable usage charge (per-unit or tiered), before discount. */
  usageMicroUsd: number;
  /** Revenue-share charge, before discount. */
  revenueShareMicroUsd: number;
  /** Discount applied (on the variable portion), in micro USD. */
  discountMicroUsd: number;
  /** Effective per-unit price after discount (0 when units is 0). */
  effectiveUnitPriceMicroUsd: number;
}

export class PricingEngine {
  /** Compute a price quote for the given plan and usage. */
  quote(plan: PricingPlan, usage: Usage): PriceQuote {
    const units = Math.max(0, Math.floor(usage.units));
    const revenue = Math.max(0, usage.revenueMicroUsd ?? 0);

    let baseFee = 0;
    let usageCost = 0;
    let revenueShare = 0;

    switch (plan.model) {
      case 'flat':
        baseFee = plan.baseFeeMicroUsd ?? 0;
        break;
      case 'per_unit':
        usageCost = (plan.unitPriceMicroUsd ?? 0) * units;
        break;
      case 'revenue_based':
        revenueShare = Math.round((plan.revenueSharePct ?? 0) * revenue);
        break;
      case 'hybrid':
        baseFee = plan.baseFeeMicroUsd ?? 0;
        usageCost = (plan.unitPriceMicroUsd ?? 0) * units;
        revenueShare = Math.round((plan.revenueSharePct ?? 0) * revenue);
        break;
      case 'tiered':
        usageCost = this.tieredCost(plan.tiers ?? [], units);
        break;
    }

    const subtotal = baseFee + usageCost + revenueShare;

    // Volume discount applies to the variable portion (usage + revenue share),
    // never to the fixed base fee.
    let discount = 0;
    const vd = plan.volumeDiscount;
    if (vd && units >= vd.minUnits) {
      discount = Math.round((usageCost + revenueShare) * vd.discountPct);
    }

    const total = Math.max(0, subtotal - discount);
    const effectiveUnitPrice = units > 0 ? Math.round(total / units) : 0;

    return {
      model: plan.model,
      totalMicroUsd: total,
      baseFeeMicroUsd: baseFee,
      usageMicroUsd: usageCost,
      revenueShareMicroUsd: revenueShare,
      discountMicroUsd: discount,
      effectiveUnitPriceMicroUsd: effectiveUnitPrice,
    };
  }

  /** Sum tiered per-unit costs across the ordered tiers for `units` units. */
  private tieredCost(tiers: Tier[], units: number): number {
    let remaining = units;
    let prevUpTo = 0;
    let total = 0;
    for (const tier of tiers) {
      if (remaining <= 0) break;
      const tierUnits = Math.min(remaining, tier.upTo - prevUpTo);
      if (tierUnits > 0) {
        total += tierUnits * tier.unitPriceMicroUsd;
        remaining -= tierUnits;
      }
      prevUpTo = tier.upTo;
    }
    return total;
  }
}
